apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: trino-claim0
  name: trinocatalogpvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
